#! /bin/sh

cd $(dirname "${0}")
cd ..

Link ()
{
	ln --symbolic --relative --force "${@}"
}

Link \
	Preferences.sublime-settings \
	~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings

Link \
	Default\ \(Linux\).sublime-keymap \
	~/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-keymap

echo OK
