#! /bin/sh

cd $(dirname "${0}")
cd ..

Link ()
{
	ln --symbolic --relative --force "${@}"
}

LinkSame ()
{
	Link \
		"${1}" \
		"${HOME}/.config/sublime-text-3/Packages/User/${1}"
}

LinkSame Preferences.sublime-settings
LinkSame Default\ \(Linux\).sublime-keymap
LinkSame scope_hunter.sublime-settings
LinkSame bh_core.sublime-settings
LinkSame ApplySyntax.sublime-settings
LinkSame Word\ Highlight.sublime-settings

echo OK
